const initialProducts = [
  { id: 1, name: 'Arroz Diana 1 kg', category: 'Despensa', barcode: '7701234567890', cost: 3200, margin: 25, stock: 18, icon: '🍚' },
  { id: 2, name: 'Aceite vegetal 900 ml', category: 'Despensa', barcode: '7701234567891', cost: 5400, margin: 28, stock: 7, icon: '🫗' },
  { id: 3, name: 'Leche entera 1 L', category: 'Lácteos', barcode: '7701234567892', cost: 3800, margin: 22, stock: 24, icon: '🥛' },
  { id: 4, name: 'Huevos x 12', category: 'Lácteos', barcode: '7701234567893', cost: 6800, margin: 20, stock: 4, icon: '🥚' },
  { id: 5, name: 'Café molido 250 g', category: 'Despensa', barcode: '7701234567894', cost: 8900, margin: 30, stock: 12, icon: '☕' },
  { id: 6, name: 'Pan tajado', category: 'Panadería', barcode: '7701234567895', cost: 4500, margin: 25, stock: 9, icon: '🍞' },
  { id: 7, name: 'Azúcar 1 kg', category: 'Despensa', barcode: '7701234567896', cost: 2700, margin: 27, stock: 31, icon: '🧂' },
  { id: 8, name: 'Gaseosa 1.5 L', category: 'Bebidas', barcode: '7701234567897', cost: 4200, margin: 35, stock: 16, icon: '🥤' },
  { id: 9, name: 'Atún en lata', category: 'Despensa', barcode: '7701234567898', cost: 5100, margin: 24, stock: 8, icon: '🥫' },
  { id: 10, name: 'Jabón de baño', category: 'Higiene', barcode: '7701234567899', cost: 2300, margin: 32, stock: 20, icon: '🧼' },
  { id: 11, name: 'Papas fritas', category: 'Snacks', barcode: '7701234567800', cost: 1800, margin: 40, stock: 14, icon: '🥔' },
  { id: 12, name: 'Agua botella 600 ml', category: 'Bebidas', barcode: '7701234567801', cost: 1200, margin: 45, stock: 27, icon: '💧' }
];
const users = [
  { id: 'owner', name: 'María Rodríguez', role: 'Dueña del negocio', pin: '1234', initials: 'MR' },
  { id: 'cashier-one', name: 'Juan García', role: 'Cajero 1', pin: '1111', initials: 'JG' },
  { id: 'cashier-two', name: 'Ana López', role: 'Cajera 2', pin: '2222', initials: 'AL' }
];
const money = value => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
let products = JSON.parse(localStorage.getItem('market-products')) || initialProducts;
let cart = []; let sales = JSON.parse(localStorage.getItem('market-sales')) || []; let selectedCategory = 'Todos'; let stream; let selectedUser = users[0]; let editingProductId = null;
const $ = selector => document.querySelector(selector); const priceOf = product => Math.round(product.cost * (1 + product.margin / 100) / 50) * 50;
function save() { localStorage.setItem('market-products', JSON.stringify(products)); localStorage.setItem('market-sales', JSON.stringify(sales)); }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2600); }
function renderCategories() { const categories = ['Todos', ...new Set(products.map(product => product.category))]; $('#categoryPills').innerHTML = categories.map(category => `<button class="${category === selectedCategory ? 'active' : ''}" data-category="${category}">${category}</button>`).join(''); }
function renderProducts() { const query = $('#productSearch').value.toLowerCase(); const filtered = products.filter(product => (selectedCategory === 'Todos' || product.category === selectedCategory) && `${product.name} ${product.barcode}`.toLowerCase().includes(query)); $('#productCount').textContent = `${filtered.length} productos disponibles`; $('#productGrid').innerHTML = filtered.map(product => `<button class="product-card" data-product="${product.id}" ${product.stock < 1 ? 'disabled' : ''}><div class="product-art">${product.icon}</div><div class="product-info"><div><span class="product-name">${product.name}</span><span class="product-meta ${product.stock <= 5 ? 'stock-low' : ''}">${product.stock <= 5 ? `Solo ${product.stock} disponibles` : `${product.stock} en stock`}</span></div><span class="product-price">${money(priceOf(product))}</span></div><span class="add-product">+</span></button>`).join('') || '<div class="no-results">No encontramos ese producto.</div>'; }
function renderCart() { $('#cartItems').innerHTML = cart.map(item => `<div class="cart-item"><div class="cart-item-art">${item.product.icon}</div><div class="cart-item-main"><strong>${item.product.name}</strong><small>${money(priceOf(item.product))} c/u</small></div><div class="quantity"><button data-action="decrease" data-id="${item.product.id}">−</button><span>${item.quantity}</span><button data-action="increase" data-id="${item.product.id}">+</button></div><span class="cart-item-price">${money(priceOf(item.product) * item.quantity)}</span></div>`).join(''); const total = cart.reduce((sum, item) => sum + priceOf(item.product) * item.quantity, 0); $('#cartEmpty').style.display = cart.length ? 'none' : 'flex'; $('#subtotal').textContent = money(total); $('#cartTotal').textContent = money(total); $('#chargeButton').disabled = !cart.length; }
function renderInventory() { const value = products.reduce((sum, product) => sum + product.cost * product.stock, 0); $('#inventoryValue').textContent = money(value); $('#activeProducts').textContent = products.length; const low = products.filter(product => product.stock <= 5).length; $('#lowStockCount').textContent = low; $('#lowStockBadge').textContent = low; $('#inventoryTable').innerHTML = products.map(product => `<tr><td>${product.icon} &nbsp;${product.name}</td><td>${product.barcode}</td><td><span class="stock-number ${product.stock <= 5 ? 'low' : ''}">${product.stock} und.</span></td><td>${money(product.cost)}</td><td><input class="margin-input" type="number" min="0" max="200" value="${product.margin}" data-margin="${product.id}" /> %</td><td class="price-cell">${money(priceOf(product))}</td><td><button class="edit-button" data-edit="${product.id}">Editar</button></td></tr>`).join(''); }
function renderReports() { const total = sales.reduce((sum, sale) => sum + sale.total, 0); const units = sales.reduce((sum, sale) => sum + sale.items.reduce((itemSum, item) => itemSum + item.quantity, 0), 0); const profit = sales.reduce((sum, sale) => sum + sale.items.reduce((itemSum, item) => itemSum + ((item.unitPrice ?? priceOf(item.product)) - (item.unitCost ?? item.product.cost)) * item.quantity, 0), 0); $('#dayTotal').textContent = money(total); $('#saleSummary').textContent = `${sales.length} ${sales.length === 1 ? 'venta registrada' : 'ventas registradas'}`; $('#averageTicket').textContent = money(sales.length ? total / sales.length : 0); $('#unitsSold').textContent = units; $('#profitTotal').textContent = money(profit); const counts = {}; sales.flatMap(sale => sale.items).forEach(item => { counts[item.product.name] = (counts[item.product.name] || 0) + item.quantity; }); const top = Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, 5); $('#topProducts').innerHTML = top.length ? top.map(([name, count]) => `<div class="top-product-row"><strong>${name}</strong><div class="bar" style="max-width:${Math.max(25, count / Math.max(top[0][1], 1) * 100)}%"></div><span>${count} und.</span></div>`).join('') : '<p class="section-heading"><span>Aún no hay ventas en esta jornada.</span></p>'; }
function renderAll() { renderCategories(); renderProducts(); renderCart(); renderInventory(); renderReports(); }
function addToCart(product) { const item = cart.find(entry => entry.product.id === product.id); if (item) { if (item.quantity < product.stock) item.quantity++; else return toast('No hay más unidades disponibles'); } else cart.push({ product, quantity: 1 }); renderCart(); }
document.addEventListener('click', event => { const tab = event.target.closest('.nav-tab'); if (tab) { if (tab.dataset.view === 'reports' && selectedUser.role !== 'Dueña del negocio') return toast('Solo la dueña puede ver las ventas y ganancias'); document.querySelectorAll('.nav-tab').forEach(button => button.classList.remove('active')); tab.classList.add('active'); document.querySelectorAll('.view').forEach(view => view.classList.remove('active')); $(`#${tab.dataset.view}View`).classList.add('active'); $('#pageTitle').textContent = tab.dataset.view === 'pos' ? 'Punto de venta' : tab.dataset.view === 'inventory' ? 'Inventario' : 'Cierre de jornada'; return; } const category = event.target.closest('[data-category]'); if (category) { selectedCategory = category.dataset.category; renderCategories(); renderProducts(); return; } const productButton = event.target.closest('[data-product]'); if (productButton) addToCart(products.find(product => product.id === Number(productButton.dataset.product))); const cartAction = event.target.closest('[data-action]'); if (cartAction) { const item = cart.find(entry => entry.product.id === Number(cartAction.dataset.id)); if (cartAction.dataset.action === 'increase') addToCart(item.product); else item.quantity--; cart = cart.filter(entry => entry.quantity > 0); renderCart(); } const close = event.target.closest('[data-close]'); if (close) closeModal(close.dataset.close); });
$('#productSearch').addEventListener('input', renderProducts); $('#clearSearch').addEventListener('click', () => { $('#productSearch').value = ''; selectedCategory = 'Todos'; renderAll(); }); $('#clearCart').addEventListener('click', () => { cart = []; renderCart(); });
$('#chargeButton').addEventListener('click', () => { $('#modalTotal').textContent = $('#cartTotal').textContent; $('#cashReceived').value = ''; $('#changeAmount').textContent = money(0); $('#paymentModal').classList.add('open'); setTimeout(() => $('#cashReceived').focus(), 50); }); $('#cashReceived').addEventListener('input', updateChange); $('#quickCash').addEventListener('click', event => { if (!event.target.dataset.cash) return; const total = cart.reduce((sum, item) => sum + priceOf(item.product) * item.quantity, 0); $('#cashReceived').value = event.target.dataset.cash === 'exact' ? total : event.target.dataset.cash; updateChange(); }); function updateChange() { const total = cart.reduce((sum, item) => sum + priceOf(item.product) * item.quantity, 0); const cash = Number($('#cashReceived').value) || 0; $('#changeAmount').textContent = money(Math.max(0, cash - total)); $('#confirmPayment').disabled = cash < total; }
$('#confirmPayment').addEventListener('click', () => { const total = cart.reduce((sum, item) => sum + priceOf(item.product) * item.quantity, 0); cart.forEach(item => { const product = products.find(product => product.id === item.product.id); product.stock -= item.quantity; }); sales.push({ total, cashier: selectedUser.name, items: cart.map(item => ({ product: item.product, quantity: item.quantity, unitPrice: priceOf(item.product), unitCost: item.product.cost })) }); cart = []; save(); closeModal('paymentModal'); renderAll(); toast('Venta guardada correctamente'); });
function closeModal(id) { $(`#${id}`).classList.remove('open'); if (id === 'cameraModal' && stream) { stream.getTracks().forEach(track => track.stop()); stream = null; } } document.querySelectorAll('.modal-backdrop').forEach(backdrop => backdrop.addEventListener('click', event => { if (event.target === backdrop) closeModal(backdrop.id); }));
$('#cameraButton').addEventListener('click', async () => { $('#cameraModal').classList.add('open'); $('#barcodeInput').value = ''; if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) { $('#cameraMessage').textContent = 'La cámara necesita abrirse desde un enlace HTTPS'; return; } try { stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); $('#cameraVideo').srcObject = stream; if (!('BarcodeDetector' in window)) { $('#cameraMessage').textContent = 'Cámara activa; escribe el código si no se detecta automáticamente'; return; } const detector = new BarcodeDetector({ formats: ['ean_13', 'ean_8', 'upc_a', 'upc_e', 'code_128'] }); $('#cameraMessage').textContent = 'Apunta al código de barras'; const scan = async () => { if (!stream) return; try { const codes = await detector.detect($('#cameraVideo')); if (codes.length) { const product = products.find(item => item.barcode === codes[0].rawValue); if (product) { addToCart(product); closeModal('cameraModal'); toast(`${product.name} agregado`); } else $('#cameraMessage').textContent = 'Código no registrado'; } } catch (_) {} requestAnimationFrame(scan); }; scan(); } catch (_) { $('#cameraMessage').textContent = 'Permite el acceso a la cámara o escribe el código'; } }); $('#manualBarcodeButton').addEventListener('click', () => { const product = products.find(item => item.barcode === $('#barcodeInput').value.trim()); if (product) { addToCart(product); closeModal('cameraModal'); toast(`${product.name} agregado`); } else toast('Código no encontrado en el inventario'); });
document.addEventListener('change', event => { if (event.target.dataset.margin) { const product = products.find(item => item.id === Number(event.target.dataset.margin)); product.margin = Number(event.target.value) || 0; save(); renderInventory(); renderProducts(); toast(`Margen actualizado para ${product.name}`); } }); $('#closeDayButton').addEventListener('click', () => { if (!sales.length) return toast('No hay ventas para cerrar todavía'); toast(`Jornada cerrada por ${money(sales.reduce((sum, sale) => sum + sale.total, 0))}`); });
function updateDateTime() { const now = new Date(); $('#currentTime').textContent = now.toLocaleTimeString('es-CO', { hour:'2-digit', minute:'2-digit' }); $('#currentDate').textContent = now.toLocaleDateString('es-CO', { weekday:'long', day:'numeric', month:'long' }).toUpperCase(); }
updateDateTime(); setInterval(updateDateTime, 1000); renderAll();
if ('serviceWorker' in navigator && window.isSecureContext) navigator.serviceWorker.register('sw.js');

function openProductModal(product) {
  editingProductId = product ? product.id : null;
  $('#productModalTitle').textContent = product ? 'Editar producto' : 'Nuevo producto';
  $('#newProductName').value = product?.name || '';
  $('#newProductBarcode').value = product?.barcode || '';
  $('#newProductCategory').value = product?.category || 'Despensa';
  $('#newProductIcon').value = product?.icon || '🛒';
  $('#newProductCost').value = product?.cost || '';
  $('#newProductStock').value = product?.stock ?? '';
  $('#newProductMargin').value = product?.margin ?? 25;
  $('#productModal').classList.add('open');
}
$('#addProductButton').addEventListener('click', () => openProductModal());
document.addEventListener('click', event => {
  const editButton = event.target.closest('[data-edit]');
  if (editButton) openProductModal(products.find(product => product.id === Number(editButton.dataset.edit)));
  if (event.target.closest('.help-button')) toast('Usa Punto de venta para cobrar o Inventario para administrar productos');
  if (event.target.closest('.icon-button')) toast('No tienes notificaciones nuevas');
  if (event.target.closest('.more-button')) toast('Sesión activa: Juan García');
});
$('#saveProductButton').addEventListener('click', () => {
  const name = $('#newProductName').value.trim();
  const barcode = $('#newProductBarcode').value.trim();
  const cost = Number($('#newProductCost').value);
  const stock = Number($('#newProductStock').value);
  if (!name || !barcode || !cost || stock < 0) return toast('Completa nombre, código, costo y stock');
  const data = { name, barcode, category: $('#newProductCategory').value.trim() || 'Despensa', icon: $('#newProductIcon').value.trim() || '🛒', cost, stock, margin: Number($('#newProductMargin').value) || 0 };
  if (editingProductId) Object.assign(products.find(product => product.id === editingProductId), data);
  else products.push({ id: Date.now(), ...data });
  save(); closeModal('productModal'); renderAll(); toast(editingProductId ? 'Producto actualizado' : 'Producto agregado');
});
document.addEventListener('keydown', event => {
  if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); $('#productSearch').focus(); }
});

function renderLoginUsers() { $('#userList').innerHTML = users.map(user => `<button class="user-option" data-user="${user.id}"><span class="user-avatar">${user.initials}</span><span><strong>${user.name}</strong><small>${user.role}</small></span></button>`).join(''); }
function finishLogin() { sessionStorage.setItem('market-user', selectedUser.id); $('#loginScreen').style.display = 'none'; $('#activeUser').textContent = `${selectedUser.name} · ${selectedUser.role}`; $('.sidebar-footer strong').textContent = selectedUser.name; $('.sidebar-footer small').textContent = selectedUser.role; }
renderLoginUsers();
$('#userList').addEventListener('click', event => { const option = event.target.closest('[data-user]'); if (!option) return; selectedUser = users.find(user => user.id === option.dataset.user); document.querySelectorAll('.user-option').forEach(item => item.classList.remove('selected')); option.classList.add('selected'); $('#loginPin').focus(); });
$('#loginButton').addEventListener('click', () => { if ($('#loginPin').value !== selectedUser.pin) { $('#loginError').textContent = 'PIN incorrecto. Intenta nuevamente.'; return; } $('#loginError').textContent = ''; finishLogin(); });
const savedUser = users.find(user => user.id === sessionStorage.getItem('market-user'));
if (savedUser) { selectedUser = savedUser; finishLogin(); }